version: "3"

services:
  mysql:
    image: docker.lawrenceli.me/mysql:8.4
    container_name: spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /var/tmp/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: docker.lawrenceli.me/redis:latest
    container_name: spring-redis
    ports:
      - "6379:6379"
#  spring:
#    build:
#      context: ./
#    image: spring-app:latest
#    container_name: spring-app
#    environment:
#      - MYSQL_URL=r2dbc:mysql://mysql:3306/spring
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    depends_on:
#      - mysql
#      - redis
#    ports:
#      - "8080:8080"